### ISSUE TITLE
Remove bootstrap theme / dependency

### ISSUE THREAD

**Issue by webdevilopers** [mremi/ContactBundle#17]
I've seen many Symfony2 bundles that are removing their Javascript and Style dependencies and leave it up to the developer to include their favorite libraries.

Personally I already use Bootstrap. Since Symfony **2.6** a form theme has been added for twig:
http://symfony.com/blog/new-in-symfony-2-6-bootstrap-form-theme

I removed the `MremiContactBundle:Contact:bootstrap_form_theme.html.twig`:
https://github.com/mremi/ContactBundle/blob/master/Resources/views/Contact/index.html.twig#L16

My bootstrap styles for instance already come with the `SonataCodeBundle`:
```twig
<link rel="stylesheet" href="{{ asset('/bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css') }}">
```
so I could remove the `bundles/mremibootstrap/css` too:
https://github.com/mremi/ContactBundle/blob/master/Resources/views/Contact/index.html.twig#L20-23

Enable the twig form theme:
```yml
# app/config.yml
twig:
    form:
        resources:
            - 'bootstrap_3_layout.html.twig'
```

and the Contact Form looks just fine.

What do you think about it, @mremi ?

Related issues:
- https://github.com/mremi/ContactBundle/issues/9
- https://github.com/mremi/ContactBundle/issues/5

**Comment by mremi** [comment]
Done in f58ee27f4918a13429c9a7674b939db49508afd0
