### ISSUE TITLE
Updating the bundle caused an error about the captcha

### ISSUE THREAD

**Issue by numerogeek** [mremi/ContactBundle#24]
Hello,

got an error since the last update.

My updated config :

mremi_contact:
    store_data:            true
    contact_class:         Application\Mremi\ContactBundle\Entity\Contact

    form:
        type:              mremi_contact
        name:              contact_form
        validation_groups: [Default]
        subject_provider:  mremi_contact.subject_provider.noop
        captcha_disabled:  true
        captcha_type:      genemu_captcha # or genemu_recaptchae

Few days ago captcha_type was ~ and worked.
Now I have to give one even if I disabled it ?

the error  I have :

Updating the "app/config/parameters.yml" file

  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
  Unrecognized option "captcha_disabled" under "mremi_contact.form"

**Comment by mremi** [comment]
Hi @numerogeek ,

Yes there was a BC break few weeks ago, you can see it in the `CHANGELOG.md`.
`captcha_disabled` was deleted, now if you don't want any captcha, just remove the `captcha_type` or set it to null (~).

**Comment by numerogeek** [comment]
Great, Merci Rémi !
