### ISSUE TITLE
Need some change

### ISSUE THREAD

**Issue by ruscon** [mremi/ContactBundle#28]
Hi, thanks for the bundle.

Can you add some refactoring ?

1. change private to protected attributes. For example, in ContactType. Or add get methods
2. add config parameters for all templates
3. need test with sonata:easy-extends

**Comment by mremi** [comment]
Hi I'm off for a week but you can create a PR if you want. Thanks

**Comment by mremi** [comment]
Hi @ruscon ,

Do you want to contribute?
