### ISSUE TITLE
probleme in production mode to send

### ISSUE THREAD

**Issue by xorgxx** [mremi/ContactBundle#29]
Hi i have same problemes to send in production mode, but only on my server "gandi".
i try in local and both work well i mean dev and prod, i take the same projet install on my "gandi2 server and there it pass all validation and give the confimation and never recieve any email !??

can you help?

the vers: "symfony/symfony": "2.6.6", "mremi/contact-bundle": "v1.1.0",
thank

config : 
```
    mailer_transport: smtp
    mailer_host: mail.gandi.net
    mailer_user: service@xxxxx.com
    mailer_password: ------
    mailer_port: 465
    mailer_encrypt: ssl
```
```
mremi_contact:
    store_data:            true
    contact_class:         Neo\ContactBundle\Entity\Contact

    form:
        type:              mremi_contact
        name:              contact_form
        validation_groups: [Default]
        subject_provider:  mremi_contact.subject_provider.noop
#        captcha_type:      ~ # or genemu_recaptcha

    email:
        mailer:            mremi_contact.mailer.twig_swift
        recipient_address: service@xxxx.com
#        from:              []
#        to:
#            - { address: service@xxxx.com, name: "Webmaster" }
        template:          MremiContactBundle:Contact:email.txt.twig
```

**Comment by mremi** [comment]
Hi,

This probably comes from your production config: from the Swift config or from your mail server. Did you look at the mail logs?

**Comment by xorgxx** [comment]
no i don't have any log. it simce that all is good but email never come

**Comment by mremi** [comment]
No log in /var/log/mail* ?

**Comment by xorgxx** [comment]
not at all !! phpmail.log empty all are empty
just try to spool be files and it creat the file in root. i my going to send by command to see

**Comment by xorgxx** [comment]
so i try to send by 
$ php app/console swiftmailer:spool:send --env=prod

resultat : 
[2015-05-05 06:05:15] Processing default mailer... 0 emails sent

**Comment by mremi** [comment]
Hi,

Empty logs means your mail server does not receive any data, so the problem is probably due to your Swift mailer config. Moreover it works on your local server.
