### ISSUE TITLE
Add posibility to change the action URL

### ISSUE THREAD

**Issue by firestorm23** [mremi/ContactBundle#42]
Hi. Can you please add posibility to change the route that used to submit the form? I mean, I can alter controller and view for the contact form, but your factory does not provide a way to pass my own action URL. 

'createForm' method in 'Mremi\ContactBundle\Form\Factory\FormFactory' looks like this

```php
    public function createForm($data = null)
    {
        return $this->formFactory->createNamed($this->name, $this->type, $data, array(
            'validation_groups' => $this->validationGroups,
        ));
    }
```
Or I can make a PR, that is not so complex change.

**Comment by firestorm23** [comment]
Nvm, you can close it, action in your bundle is set in view.

**Comment by mremi** [comment]
Hi @firestorm23, absolutely ;)
